# Generated by Django 2.1.3 on 2019-12-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bearing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default='blank'),
        ),
    ]
